# Generated by Django 6.0 on 2026-01-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='categorical_feature1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='continuous_feature1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='record',
            name='continuous_feature2',
            field=models.FloatField(default=0.0),
        ),
    ]
