# Generated by Django 6.0 on 2026-01-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_record_categorical_feature1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='categorical_feature1',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='record',
            name='continuous_feature1',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='record',
            name='continuous_feature2',
            field=models.FloatField(default=None),
        ),
    ]
