# Generated by Django 6.0 on 2026-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0003_alter_record_categorical_feature1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='categorical_feature1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='continuous_feature1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='continuous_feature2',
            field=models.FloatField(null=True),
        ),
    ]
